### ISSUE TITLE
Sum of array

### ISSUE THREAD

**Issue by yuvrajjwala** [yuvrajjwala/-sumOfArray#1]
I want to add elements of array but I can't.
Please help

**Comment by ShouryaBrahmastra** [comment]
Sir can you please assign me this task 
would like to perform this using C languague.

**Comment by AbhirupB** [comment]
Please put the Hacktoberfest 2021 label. Thank You!

**Comment by Ankitsh-rtx** [comment]
sir please assign me this task i would do it in java

**Comment by Ankitsh-rtx** [comment]
please assign me this task
would do it in c++

**Comment by yuvrajjwala** [comment]
Issue Resolved.
